services:
   app:
      build:
        context: ./app
        dockerfile: Dockerfile
      container_name: PYTHON
      # volumes:
      #   - ./app/files:/files
      volumes:
        - ./app:/app
      tty: true
      stdin_open: true
      command: /bin/bash -c "cp -n config.yml.example config.yml && python app.py"